version: 0.0
os: linux
files:
  - source: /testProject.zip
    destination: /opt/apache-tomcat-9.0.41/webapps/
hooks:
  AfterInstall:
    - location: scripts/AfterInstall
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

